manifest:

  defaults:
    remote: zephyrproject

  remotes:
    - name: zephyrproject
      url-base: https://github.com/zephyrproject-rtos


  projects:
    - name: zephyr
      remote: zephyrproject
      # TODO: consider update to f9e3b65d3a9794ee2233aa88172346f887b48d04, will need to change some POSIX API config though.
      revision: v3.7.0
      import:
        path-prefix: deps

  self:
    path: application